columns:
  - elevation: int
  - aspect: int
  - slope: int
  - horizontal_distance_to_hydrology: int
  - Vertical_Distance_To_Hydrology: int
  - Horizontal_Distance_To_Roadways: int
  - Horizontal_Distance_To_Fire_Points: int
  - wilderness_area1: int
  - wilderness_area2: int
  - wilderness_area3: int
  - wilderness_area4: int
  - soil_type_1: int
  - soil_type_2: int
  - soil_type_3: int
  - soil_type_4: int
  - soil_type_5: int
  - soil_type_6: int
  - soil_type_8: int
  - soil_type_9: int
  - soil_type_10: int
  - soil_type_11: int
  - soil_type_12: int
  - soil_type_13: int
  - soil_type_14: int
  - soil_type_15: int
  - soil_type_16: int
  - soil_type_17: int
  - soil_type_18: int
  - soil_type_19: int
  - soil_type_20: int
  - soil_type_21: int
  - soil_type_22: int
  - soil_type_23: int
  - soil_type_24: int
  - soil_type_25: int
  - soil_type_26: int
  - soil_type_27: int
  - soil_type_28: int
  - soil_type_29: int
  - soil_type_30: int
  - soil_type_31: int
  - soil_type_32: int
  - soil_type_33: int
  - soil_type_34: int
  - soil_type_35: int
  - soil_type_36: int
  - soil_type_37: int
  - soil_type_38: int
  - soil_type_39: int
  - soil_type_40: int
  - Cover_Type: category


numerical_columns:
  - Elevation
  - Aspect
  - Slope
  - Horizontal_Distance_To_Hydrology
  - Vertical_Distance_To_Hydrology
  - Horizontal_Distance_To_Roadways
  - Horizontal_Distance_To_Fire_Points
  - Wilderness_Area1
  - Wilderness_Area2
  - Wilderness_Area3
  - Wilderness_Area4
  - Soil_Type1
  - Soil_Type2
  - Soil_Type3
  - Soil_Type4
  - Soil_Type5
  - Soil_Type6
  - Soil_Type9
  - Soil_Type10
  - Soil_Type11
  - Soil_Type12
  - Soil_Type13
  - Soil_Type14
  - Soil_Type16
  - Soil_Type17
  - Soil_Type18
  - Soil_Type19
  - Soil_Type20
  - Soil_Type21
  - Soil_Type22
  - Soil_Type23
  - Soil_Type24
  - Soil_Type25
  - Soil_Type26
  - Soil_Type27
  - Soil_Type28
  - Soil_Type29
  - Soil_Type30
  - Soil_Type31
  - Soil_Type32
  - Soil_Type33
  - Soil_Type34
  - Soil_Type35
  - Soil_Type37
  - Soil_Type38
  - Soil_Type39
  - Soil_Type40

categorical_columns:
  - Cover_Type

drop_columns:
  - Soil_Type7
  - Soil_Type8
  - Soil_Type15
  - Soil_Type36